version: '2'

services:
  mysql:
    image: mysql:5.6
    hostname: eschool-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
  
    ports:
    - "3306:3306"
   # volumes:
   # - /srv/docker/redmine/mysql:/var/lib/mysql


  backend:
    image: eschool:1.0
    hostname: eschool-backend
    restart: always
    depends_on:
    - mysql
    ports:
    - "8080:8080"
    
   # volumes:
   # - /srv/docker/redmine/redmine_mysql:/home/redmine/data


  frontend:
    image: itca_front:v1
    hostname: eschool-frontend
    restart: always
    depends_on:
    - backend
    ports:
    - "80:80"
    
    #volumes:
    # - /srv/docker/redmine/redmine_mysql:/home/redmine/data

    