version: '2'

services:
  mysql:
    image: mysql:5.6
    hostname: eschool-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
    ports:
    - "3306:3306"
    networks: 
    - eschool-network

    volumes:
    - /srv/docker/eSchool-mysql-se/mysql:/var/lib/mysql

  backend:
    image: eschool:1.2
    hostname: eschool-backend
    restart: always
    environment:
    - MYSQL_DATABASE=eschool
    - DATASOURCE_URL=jdbc:mysql://eschool-mysql:3306/eschool?useUnicode=true&characterEncoding=utf8
    - DATASOURCE_USERNAME=root
    - DATASOURCE_PASSWORD=root
    depends_on:
    - mysql
    ports:
    - "8180:8080"
    networks: 
    - eschool-network

  backend2:
    image: eschool:1.2
    hostname: eschool-backend2
    restart: always
    environment:
    - MYSQL_DATABASE=eschool
    - DATASOURCE_URL=jdbc:mysql://eschool-mysql:3306/eschool?useUnicode=true&characterEncoding=utf8
    - DATASOURCE_USERNAME=root
    - DATASOURCE_PASSWORD=root
    depends_on:
    - mysql
    ports:
    - "8190:8080"
    networks: 
    - eschool-network

  frontend:
    image: itca_front_https:v1.4 
    hostname: eschool-frontend
    restart: always
    depends_on:
    - backend
    ports:
    - "88:80"
    networks: 
    - eschool-network

  frontend2:
    image: itca_front_https_se:v1.4
    hostname: eschool-frontend2
    restart: always
    depends_on:
    - backend2
    ports:
    - "99:80"
    networks: 
    - eschool-network

  balancer:
    image: nginx-upstream:1.5    
    hostname: eschool-balancer
  #  restart: always
    depends_on:
    - frontend
    - frontend2
   
    volumes:
     - type: bind
       source: /srv/docker/eSchool-nginx/nginx.conf
       target: /etc/nginx/nginx.conf
     - type: bind
       source: /etc/letsencrypt/archive/eschool.devops.uno
       target: /home/user/letsencrypt/data/certs 
    ports:
    - "80:80"
    - "443:443"    
    - "8080:8080"
    - "8090:8090"
    networks: 
    - eschool-network

networks:
  eschool-network:
    driver: bridge